# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk11
# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres
  - psql -c 'create database parsersql;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo.
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту (Указать свою), если сборка упала.
notifications:
  email:
    recipients:
    - teaching-light@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="2273920f-5349-492a-80d5-52f62c0f4a06"